global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: my-project
rule_files:
- alert.rules
alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - alertmanager:9093
scrape_configs:
- job_name: prometheus
  scrape_interval: 5s
  static_configs:
  - targets:
    - localhost:9090
- job_name: node-exporter
  scrape_interval: 5s
  dns_sd_configs:
  - names:
    - tasks.node-exporter
    type: A
    port: 9100
#- job_name: prometheus-rest-service
#  scrape_interval: 5s
#  metrics_path: /prometheus-rest-service-0.0.1-SNAPSHOT/metrics
#  static_configs:
#  - targets:
#    - 10.71.32.235:8080