{
 "title": "Sample services",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Span count (per min)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(jaeger_standalone:jaeger_collector:jaeger:spans_recd[1m]))"
    }
   ]
  },
  {
   "title": "Span duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(span_sum[1m])) without (pod,instance,job,namespace,endpoint,transaction,error)"
    }
   ]
  },
  {
   "title": "Service error ratio",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(sum(jaeger_standalone:jaeger:reporter_spans{result=\"err\"}) / sum(jaeger_standalone:jaeger:reporter_spans)) * 100"
    }
   ]
  }
 ]
}